### ISSUE TITLE
Week 5 Ready for review

### ISSUE THREAD

**Issue by stclassy** [stclassy/groceryListBuilder#3]
@pawaitemadisoncollege 
I didn't really have any issues with week other than forgetting to map the new java class in my test hibernate properties file. I am still having a small issue with log4j2. do you know why it would try to appand a : at the end of a log? I get an error message saying it can't rename file and shows "filepath_timestamp.log:" because of illegal character ":" but I've checked my properties file for log4j2 about 5 times now and can't fine any malformed statements.

**Comment by pawaitemadisoncollege** [comment]
Hi @stclassy This is good work with the one-to-many AND you have the generic dao implemented! You did a good job testing to make sure deleting a recipe didn't delete the user. I think it would be good to test this the other way too - if you delete the user, what happens to that user's recipes? Write a quick test to verify whatever should happen does happen. 

Regarding that logging error, I wonder if the colon is part of the time format or something and the OS doesn't like that name? I think this would be a good one to post in Slack including screenshots of the error message.  Maybe somebody else has run into this and solved it. If nothing else, we'll get more brains working on it!
